name: 714GridBeta
favicon: null
layout_spectrum: 0.17192
typography_spectrum: 0.55435
title: '714Web #TheGrid Beta Site'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#75a5a3'
    - '#ffffff'
    - '#3e7c8e'
    - '#022842'
    - '#a8c7cc'
  brandStrength: 0.5
  lightness: 0.3875699129421264
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
