name: 714GridBeta
favicon: null
layout_spectrum: 0
typography_spectrum: 0.55435
title: '714Web #TheGrid Beta Site'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#75a5a3'
    - '#ffffff'
    - '#3e7c8e'
    - '#022842'
    - '#a8c7cc'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
